### ISSUE TITLE
Losing descriptions on properties

### ISSUE THREAD

**Issue by CHamlinPNP** [lscheffler/bin2text#4]
## ℹ Computer information

- VFP version: 9.00.0000.7423
- FoxBin2PRG version: Moving from 1.19.76 -> 1.19.77
- Bin2Text version:

## 📝 Provide detailed reproduction steps (if any)

1. …Ran the two versions of FoxBin2PRG 1.19.76 and 1.19.77 on same source file
2. …Did a compare of the results
3. …Attached before and after which shows the descriptions on properties are now gone

### ✔️ Expected result

I expected the descriptions to still be there

### ❌ Actual result

Lost all descriptions on properties. So after taking the time to putting in descriptions...use of the current version will remove them all.

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_
![before](https://user-images.githubusercontent.com/34104227/226349183-fdd26673-abd3-4693-82e2-823e11ecd255.png)
![after](https://user-images.githubusercontent.com/34104227/226349199-a741c3e2-80bd-4a71-8de0-bb89d5afadf4.png)

**Comment by lscheffler** [comment]
@CHamlinPNP Somehow I missed this issue on my mail, and I never look into the github projects. I beg your pardon. This sounds more a problem of [FoxBin2Prg](https://github.com/fdbozzo/foxbin2prg) then of Bin2Text.

Also, are you sure that the descriptions in your *binaries* are gone? The whole idea of FoxBin2Prg 1.19.77 was to spilt declaration (and description) of a property from value, due to problems of special values. The comments are stored on a different section and should be restored?

If the descriptions are not restored *to binary*, please open an issue on FoxBin2Prg.
